version: '3.7'
services:
  laravel:
    image: jesusgr4/solutions-repository:laravel-server-v1.0.0
    command: bash -c "php /var/www/html/artisan migrate && php /var/www/html/artisan db:seed && php /var/www/html/artisan passport:install && php /var/www/html/artisan db:seed && php-fpm"
    build:
      context: ./laravel-server/laravel-application/
      dockerfile: Dockerfile
      args:
        - VENDOR_DIR=$ENV_VENDOR
    environment:
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_DATABASE=$DB_DATABASE
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - ENCRYPTED_KEY=$ENCRYPTED_KEY
      - ENVIRONMENT=$ENVIRONMENT
      - DEBUG_MODE=$DEBUG_MODE
      - DJANGO_HOST=$DJANGO_HOST
    restart: unless-stopped
    container_name: laravel-application
    volumes:
      - ./laravel-server/laravel-application:/var/www/html
    links:
      - db

  nginx:
    image: jesusgr4/solutions-repository:nginx-server-v1.0.0
    build:
      context: ./laravel-server/
      dockerfile: Dockerfile
      args:
        - VENDOR_DIR=$ENV_VENDOR
    container_name: server
    restart: unless-stopped
    volumes:
      - ./laravel-server/laravel-application:/var/www/html
    depends_on:
      - laravel
    ports:
      - "$HTTP_PORT:80"
    links:
      - laravel
      - db
  
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    volumes:
      - ./dbdata/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
  
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - ./dbdata/postgres:/var/lib/postgresql/data
  
  django:
    image: jesusgr4/solutions-repository:django-v1.0.0
    container_name: django-app
    build: 
      context: ./django-server/django/
      dockerfile: Dockerfile
    command: bash -c "sleep 15 && python /app/manage.py migrate && python /app/manage.py runserver 0.0.0.0:8000"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      DB_PORT_DJANGO: $DB_PORT_DJANGO
      DB_DATABASE_DJANGO: $DB_DATABASE_DJANGO
      DB_PASSWORD_DJANGO: $DB_PASSWORD_DJANGO
      DB_USERNAME_DJANGO: $DB_USERNAME_DJANGO
      DB_PASSWORD_DJANGO: $DB_PASSWORD_DJANGO
      DB_HOST_DJANGO: $DB_HOST_DJANGO
      DEFAULT_DB_CONNECTION: $DEFAULT_DB_CONNECTION
    volumes:
      - ./django-server/django/:/app/
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - db_django
        
  db_django:
    image: mysql:5.7.22
    container_name: db_django
    restart: unless-stopped
    volumes:
      - ./dbdata/djangomysql:/var/lib/mysql
    ports:
      - "$DB_PORT_DJANGO:3306"
    environment:
      MYSQL_DATABASE: $DB_DATABASE_DJANGO
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD_DJANGO
      MYSQL_USER: $DB_USERNAME_DJANGO
      MYSQL_PASSWORD: $DB_PASSWORD_DJANGO



