apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-postgres
  labels:
    app: django
spec:
  selector:
    matchLabels:
      app: django
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: django
        tier: postgres
    spec:
      containers:
      - image: postgres:latest
        name: postgres
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 300m
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: db_password
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgrescm
              key: username
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgrescm
              key: database
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-django-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-django-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim
